
MONGODB_HOST: mongodb-{{ env }}.jansi1.site # mongodb-dev.jansi1.site
REDIS_HOST: redis-{{ env }}.jansi1.site
CATALOGUE_HOST: catalogue.backend-alb-{{ env }}.jansi1.site
CART_HOST: cart.backend-alb-{{ env }}.jansi1.site
USER_HOST: user.backend-alb-{{ env }}.jansi1.site
RABBITMQ_HOST: rabbitmq-{{ env }}.jansi1.site
MYSQL_HOST: mysql-{{ env }}.jansi1.site
SHIPPING_HOST: shipping.backend-alb-{{ env }}.jansi1.site
PAYMENT_HOST: payment.backend-alb-{{ env }}.jansi1.site