MONGODB_HOST: mongodb.daws86s.fun
REDIS_HOST: redis.daws86s.fun
CATALOGUE_HOST: catalogue.daws86s.fun
CART_HOST: cart.daws86s.fun
USER_HOST: user.daws86s.fun
RABBITMQ_HOST: rabbitmq.daws86s.fun
MYSQL_HOST: mysql.daws86s.fun
SHIPPING_HOST: shipping.daws86s.fun
PAYMENT_HOST: payment.daws86s.fun


# These variables automatically apply to all hosts in that group — you don’t have to pass them manually in every playbook or role.
# | Location                    | Scope          | Example Filename      | Purpose                     |
# | --------------------------- | -------------- | --------------------- | --------------------------- |
# | `group_vars/all.yaml`       | All hosts      | `all.yaml`            | Common vars for all servers |
# | `group_vars/<group>.yaml`   | Specific group | `web.yaml`, `db.yaml` | Vars for only that group    |
# | `host_vars/<hostname>.yaml` | Specific host  | `webserver1.yaml`     | Vars for a single host      |
